// Code generated by pigeon; DO NOT EDIT.

package grammar

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "file",
			pos:  position{line: 8, col: 1, offset: 59},
			expr: &zeroOrMoreExpr{
				pos: position{line: 8, col: 8, offset: 66},
				expr: &ruleRefExpr{
					pos:  position{line: 8, col: 8, offset: 66},
					name: "line",
				},
			},
		},
		{
			name: "eol",
			pos:  position{line: 10, col: 1, offset: 76},
			expr: &choiceExpr{
				pos: position{line: 10, col: 7, offset: 82},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 10, col: 8, offset: 83},
						exprs: []any{
							&zeroOrOneExpr{
								pos: position{line: 10, col: 8, offset: 83},
								expr: &litMatcher{
									pos:        position{line: 10, col: 8, offset: 83},
									val:        "\r",
									ignoreCase: false,
									want:       "\"\\r\"",
								},
							},
							&litMatcher{
								pos:        position{line: 10, col: 14, offset: 89},
								val:        "\n",
								ignoreCase: false,
								want:       "\"\\n\"",
							},
						},
					},
					&litMatcher{
						pos:        position{line: 10, col: 22, offset: 97},
						val:        "\r",
						ignoreCase: false,
						want:       "\"\\r\"",
					},
				},
			},
		},
		{
			name: "line",
			pos:  position{line: 12, col: 1, offset: 106},
			expr: &seqExpr{
				pos: position{line: 12, col: 8, offset: 113},
				exprs: []any{
					&choiceExpr{
						pos: position{line: 12, col: 9, offset: 114},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 12, col: 9, offset: 114},
								name: "comment",
							},
							&actionExpr{
								pos: position{line: 12, col: 19, offset: 124},
								run: (*parser).callonline4,
								expr: &seqExpr{
									pos: position{line: 12, col: 19, offset: 124},
									exprs: []any{
										&labeledExpr{
											pos:   position{line: 12, col: 19, offset: 124},
											label: "code",
											expr: &ruleRefExpr{
												pos:  position{line: 12, col: 24, offset: 129},
												name: "code",
											},
										},
										&zeroOrOneExpr{
											pos: position{line: 12, col: 29, offset: 134},
											expr: &ruleRefExpr{
												pos:  position{line: 12, col: 29, offset: 134},
												name: "comment",
											},
										},
									},
								},
							},
						},
					},
					&choiceExpr{
						pos: position{line: 12, col: 60, offset: 165},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 12, col: 60, offset: 165},
								name: "eol",
							},
							&ruleRefExpr{
								pos:  position{line: 12, col: 66, offset: 171},
								name: "eof",
							},
						},
					},
				},
			},
		},
		{
			name: "comment",
			pos:  position{line: 14, col: 1, offset: 179},
			expr: &actionExpr{
				pos: position{line: 14, col: 11, offset: 189},
				run: (*parser).calloncomment1,
				expr: &seqExpr{
					pos: position{line: 14, col: 11, offset: 189},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 14, col: 11, offset: 189},
							val:        "#",
							ignoreCase: false,
							want:       "\"#\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 14, col: 15, offset: 193},
							expr: &seqExpr{
								pos: position{line: 14, col: 16, offset: 194},
								exprs: []any{
									&ruleRefExpr{
										pos:  position{line: 14, col: 16, offset: 194},
										name: "any",
									},
									&notExpr{
										pos: position{line: 14, col: 20, offset: 198},
										expr: &ruleRefExpr{
											pos:  position{line: 14, col: 21, offset: 199},
											name: "eol",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "code",
			pos:  position{line: 15, col: 1, offset: 237},
			expr: &choiceExpr{
				pos: position{line: 15, col: 8, offset: 244},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 15, col: 8, offset: 244},
						name: "directive",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 20, offset: 256},
						name: "expression",
					},
				},
			},
		},
		{
			name: "directive",
			pos:  position{line: 17, col: 1, offset: 270},
			expr: &actionExpr{
				pos: position{line: 17, col: 13, offset: 282},
				run: (*parser).callondirective1,
				expr: &seqExpr{
					pos: position{line: 17, col: 13, offset: 282},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 17, col: 13, offset: 282},
							val:        "// ",
							ignoreCase: false,
							want:       "\"// \"",
						},
						&labeledExpr{
							pos:   position{line: 17, col: 19, offset: 288},
							label: "directive",
							expr: &ruleRefExpr{
								pos:  position{line: 17, col: 30, offset: 299},
								name: "include",
							},
						},
					},
				},
			},
		},
		{
			name: "include",
			pos:  position{line: 18, col: 1, offset: 335},
			expr: &actionExpr{
				pos: position{line: 18, col: 11, offset: 345},
				run: (*parser).calloninclude1,
				expr: &seqExpr{
					pos: position{line: 18, col: 11, offset: 345},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 18, col: 11, offset: 345},
							val:        "include",
							ignoreCase: false,
							want:       "\"include\"",
						},
						&oneOrMoreExpr{
							pos: position{line: 18, col: 21, offset: 355},
							expr: &ruleRefExpr{
								pos:  position{line: 18, col: 21, offset: 355},
								name: "ws",
							},
						},
						&labeledExpr{
							pos:   position{line: 18, col: 25, offset: 359},
							label: "fn",
							expr: &ruleRefExpr{
								pos:  position{line: 18, col: 28, offset: 362},
								name: "literal",
							},
						},
					},
				},
			},
		},
		{
			name: "quotedString",
			pos:  position{line: 20, col: 1, offset: 422},
			expr: &choiceExpr{
				pos: position{line: 20, col: 16, offset: 437},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 20, col: 16, offset: 437},
						name: "singleQuotedString",
					},
					&actionExpr{
						pos: position{line: 20, col: 37, offset: 458},
						run: (*parser).callonquotedString3,
						expr: &ruleRefExpr{
							pos:  position{line: 20, col: 37, offset: 458},
							name: "doubleQuotedString",
						},
					},
				},
			},
		},
		{
			name: "singleQuotedString",
			pos:  position{line: 21, col: 1, offset: 508},
			expr: &actionExpr{
				pos: position{line: 21, col: 22, offset: 529},
				run: (*parser).callonsingleQuotedString1,
				expr: &seqExpr{
					pos: position{line: 21, col: 22, offset: 529},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 21, col: 22, offset: 529},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 21, col: 26, offset: 533},
							expr: &choiceExpr{
								pos: position{line: 21, col: 27, offset: 534},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 21, col: 27, offset: 534},
										val:        "\\'",
										ignoreCase: false,
										want:       "\"\\\\'\"",
									},
									&charClassMatcher{
										pos:        position{line: 21, col: 35, offset: 542},
										val:        "[^']",
										chars:      []rune{'\''},
										ignoreCase: false,
										inverted:   true,
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 21, col: 42, offset: 549},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
					},
				},
			},
		},
		{
			name: "doubleQuotedString",
			pos:  position{line: 22, col: 1, offset: 585},
			expr: &actionExpr{
				pos: position{line: 22, col: 22, offset: 606},
				run: (*parser).callondoubleQuotedString1,
				expr: &seqExpr{
					pos: position{line: 22, col: 22, offset: 606},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 22, col: 22, offset: 606},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 22, col: 26, offset: 610},
							expr: &choiceExpr{
								pos: position{line: 22, col: 27, offset: 611},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 22, col: 27, offset: 611},
										val:        "\\\"",
										ignoreCase: false,
										want:       "\"\\\\\\\"\"",
									},
									&charClassMatcher{
										pos:        position{line: 22, col: 36, offset: 620},
										val:        "[^\"]",
										chars:      []rune{'"'},
										ignoreCase: false,
										inverted:   true,
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 22, col: 43, offset: 627},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "expression_list",
			pos:  position{line: 26, col: 1, offset: 718},
			expr: &seqExpr{
				pos: position{line: 26, col: 19, offset: 736},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 26, col: 19, offset: 736},
						name: "expression",
					},
					&zeroOrMoreExpr{
						pos: position{line: 26, col: 30, offset: 747},
						expr: &seqExpr{
							pos: position{line: 26, col: 31, offset: 748},
							exprs: []any{
								&zeroOrMoreExpr{
									pos: position{line: 26, col: 31, offset: 748},
									expr: &ruleRefExpr{
										pos:  position{line: 26, col: 31, offset: 748},
										name: "ws",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 26, col: 35, offset: 752},
									name: "expression",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "call",
			pos:  position{line: 27, col: 1, offset: 767},
			expr: &seqExpr{
				pos: position{line: 27, col: 8, offset: 774},
				exprs: []any{
					&labeledExpr{
						pos:   position{line: 27, col: 8, offset: 774},
						label: "_i",
						expr: &ruleRefExpr{
							pos:  position{line: 27, col: 11, offset: 777},
							name: "identifier",
						},
					},
					&litMatcher{
						pos:        position{line: 27, col: 22, offset: 788},
						val:        "(",
						ignoreCase: false,
						want:       "\"(\"",
					},
					&labeledExpr{
						pos:   position{line: 27, col: 26, offset: 792},
						label: "_m",
						expr: &zeroOrOneExpr{
							pos: position{line: 27, col: 29, offset: 795},
							expr: &ruleRefExpr{
								pos:  position{line: 27, col: 29, offset: 795},
								name: "expression_list",
							},
						},
					},
					&litMatcher{
						pos:        position{line: 27, col: 46, offset: 812},
						val:        ")",
						ignoreCase: false,
						want:       "\")\"",
					},
				},
			},
		},
		{
			name: "index",
			pos:  position{line: 29, col: 1, offset: 819},
			expr: &actionExpr{
				pos: position{line: 29, col: 9, offset: 827},
				run: (*parser).callonindex1,
				expr: &seqExpr{
					pos: position{line: 29, col: 9, offset: 827},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 29, col: 9, offset: 827},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&labeledExpr{
							pos:   position{line: 29, col: 13, offset: 831},
							label: "_e",
							expr: &ruleRefExpr{
								pos:  position{line: 29, col: 16, offset: 834},
								name: "expression",
							},
						},
						&litMatcher{
							pos:        position{line: 29, col: 27, offset: 845},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "member",
			pos:  position{line: 31, col: 1, offset: 872},
			expr: &actionExpr{
				pos: position{line: 31, col: 10, offset: 881},
				run: (*parser).callonmember1,
				expr: &seqExpr{
					pos: position{line: 31, col: 10, offset: 881},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 31, col: 10, offset: 881},
							label: "_m",
							expr: &choiceExpr{
								pos: position{line: 31, col: 14, offset: 885},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 31, col: 14, offset: 885},
										name: "identifier",
									},
									&ruleRefExpr{
										pos:  position{line: 31, col: 27, offset: 898},
										name: "quotedString",
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 31, col: 41, offset: 912},
							label: "_e",
							expr: &zeroOrMoreExpr{
								pos: position{line: 31, col: 44, offset: 915},
								expr: &ruleRefExpr{
									pos:  position{line: 31, col: 44, offset: 915},
									name: "index",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "member_list",
			pos:  position{line: 37, col: 1, offset: 1032},
			expr: &actionExpr{
				pos: position{line: 37, col: 15, offset: 1046},
				run: (*parser).callonmember_list1,
				expr: &seqExpr{
					pos: position{line: 37, col: 15, offset: 1046},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 37, col: 15, offset: 1046},
							label: "_m",
							expr: &ruleRefExpr{
								pos:  position{line: 37, col: 18, offset: 1049},
								name: "member",
							},
						},
						&labeledExpr{
							pos:   position{line: 37, col: 25, offset: 1056},
							label: "_r",
							expr: &zeroOrMoreExpr{
								pos: position{line: 37, col: 28, offset: 1059},
								expr: &seqExpr{
									pos: position{line: 37, col: 29, offset: 1060},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 37, col: 29, offset: 1060},
											val:        ".",
											ignoreCase: false,
											want:       "\".\"",
										},
										&labeledExpr{
											pos:   position{line: 37, col: 33, offset: 1064},
											label: "_r",
											expr: &ruleRefExpr{
												pos:  position{line: 37, col: 36, offset: 1067},
												name: "member",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "reference",
			pos:  position{line: 41, col: 1, offset: 1139},
			expr: &actionExpr{
				pos: position{line: 41, col: 13, offset: 1151},
				run: (*parser).callonreference1,
				expr: &seqExpr{
					pos: position{line: 41, col: 13, offset: 1151},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 41, col: 13, offset: 1151},
							name: "sign",
						},
						&labeledExpr{
							pos:   position{line: 42, col: 3, offset: 1160},
							label: "_m",
							expr: &choiceExpr{
								pos: position{line: 43, col: 5, offset: 1171},
								alternatives: []any{
									&actionExpr{
										pos: position{line: 43, col: 5, offset: 1171},
										run: (*parser).callonreference6,
										expr: &labeledExpr{
											pos:   position{line: 43, col: 5, offset: 1171},
											label: "_m",
											expr: &choiceExpr{
												pos: position{line: 43, col: 9, offset: 1175},
												alternatives: []any{
													&ruleRefExpr{
														pos:  position{line: 43, col: 9, offset: 1175},
														name: "member_list",
													},
													&ruleRefExpr{
														pos:  position{line: 43, col: 23, offset: 1189},
														name: "expression",
													},
												},
											},
										},
									},
									&actionExpr{
										pos: position{line: 44, col: 6, offset: 1229},
										run: (*parser).callonreference11,
										expr: &seqExpr{
											pos: position{line: 44, col: 6, offset: 1229},
											exprs: []any{
												&litMatcher{
													pos:        position{line: 44, col: 6, offset: 1229},
													val:        "(",
													ignoreCase: false,
													want:       "\"(\"",
												},
												&labeledExpr{
													pos:   position{line: 44, col: 10, offset: 1233},
													label: "_m",
													expr: &ruleRefExpr{
														pos:  position{line: 44, col: 13, offset: 1236},
														name: "reference",
													},
												},
												&litMatcher{
													pos:        position{line: 44, col: 23, offset: 1246},
													val:        ")",
													ignoreCase: false,
													want:       "\")\"",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "dblquot",
			pos:  position{line: 49, col: 1, offset: 1307},
			expr: &seqExpr{
				pos: position{line: 49, col: 11, offset: 1317},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 49, col: 11, offset: 1317},
						name: "quot",
					},
					&ruleRefExpr{
						pos:  position{line: 49, col: 16, offset: 1322},
						name: "quot",
					},
				},
			},
		},
		{
			name: "template",
			pos:  position{line: 50, col: 1, offset: 1328},
			expr: &seqExpr{
				pos: position{line: 50, col: 12, offset: 1339},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 50, col: 12, offset: 1339},
						name: "dblquot",
					},
					&zeroOrMoreExpr{
						pos: position{line: 50, col: 20, offset: 1347},
						expr: &ruleRefExpr{
							pos:  position{line: 50, col: 20, offset: 1347},
							name: "ws",
						},
					},
					&labeledExpr{
						pos:   position{line: 50, col: 24, offset: 1351},
						label: "_i",
						expr: &ruleRefExpr{
							pos:  position{line: 50, col: 27, offset: 1354},
							name: "identifier",
						},
					},
					&zeroOrMoreExpr{
						pos: position{line: 50, col: 38, offset: 1365},
						expr: &ruleRefExpr{
							pos:  position{line: 50, col: 38, offset: 1365},
							name: "ws",
						},
					},
					&labeledExpr{
						pos:   position{line: 50, col: 42, offset: 1369},
						label: "_a",
						expr: &ruleRefExpr{
							pos:  position{line: 50, col: 45, offset: 1372},
							name: "argument_decl",
						},
					},
					&zeroOrMoreExpr{
						pos: position{line: 50, col: 59, offset: 1386},
						expr: &ruleRefExpr{
							pos:  position{line: 50, col: 59, offset: 1386},
							name: "comment",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 50, col: 68, offset: 1395},
						name: "eol",
					},
					&notExpr{
						pos: position{line: 50, col: 72, offset: 1399},
						expr: &ruleRefExpr{
							pos:  position{line: 50, col: 73, offset: 1400},
							name: "dblquot",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 50, col: 81, offset: 1408},
						name: "dblquot",
					},
				},
			},
		},
		{
			name: "parse",
			pos:  position{line: 51, col: 1, offset: 1417},
			expr: &seqExpr{
				pos: position{line: 51, col: 9, offset: 1425},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 51, col: 9, offset: 1425},
						name: "identifier",
					},
					&zeroOrMoreExpr{
						pos: position{line: 51, col: 20, offset: 1436},
						expr: &ruleRefExpr{
							pos:  position{line: 51, col: 20, offset: 1436},
							name: "ws",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 51, col: 24, offset: 1440},
						name: "eq",
					},
					&ruleRefExpr{
						pos:  position{line: 51, col: 27, offset: 1443},
						name: "tilda",
					},
					&ruleRefExpr{
						pos:  position{line: 51, col: 33, offset: 1449},
						name: "expression",
					},
				},
			},
		},
		{
			name: "expression",
			pos:  position{line: 53, col: 1, offset: 1463},
			expr: &choiceExpr{
				pos: position{line: 54, col: 3, offset: 1479},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 54, col: 3, offset: 1479},
						name: "parse",
					},
					&ruleRefExpr{
						pos:  position{line: 55, col: 3, offset: 1490},
						name: "assign",
					},
					&ruleRefExpr{
						pos:  position{line: 56, col: 3, offset: 1502},
						name: "call",
					},
					&ruleRefExpr{
						pos:  position{line: 57, col: 3, offset: 1512},
						name: "reference",
					},
					&ruleRefExpr{
						pos:  position{line: 58, col: 3, offset: 1527},
						name: "literal",
					},
					&actionExpr{
						pos: position{line: 59, col: 5, offset: 1542},
						run: (*parser).callonexpression7,
						expr: &seqExpr{
							pos: position{line: 59, col: 5, offset: 1542},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 59, col: 5, offset: 1542},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&labeledExpr{
									pos:   position{line: 59, col: 9, offset: 1546},
									label: "_e",
									expr: &ruleRefExpr{
										pos:  position{line: 59, col: 13, offset: 1550},
										name: "expression",
									},
								},
								&litMatcher{
									pos:        position{line: 59, col: 24, offset: 1561},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "block",
			pos:  position{line: 61, col: 1, offset: 1588},
			expr: &choiceExpr{
				pos: position{line: 61, col: 8, offset: 1595},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 61, col: 8, offset: 1595},
						exprs: []any{
							&litMatcher{
								pos:        position{line: 61, col: 8, offset: 1595},
								val:        "{",
								ignoreCase: false,
								want:       "\"{\"",
							},
							&zeroOrMoreExpr{
								pos: position{line: 61, col: 12, offset: 1599},
								expr: &ruleRefExpr{
									pos:  position{line: 61, col: 12, offset: 1599},
									name: "ws",
								},
							},
							&zeroOrMoreExpr{
								pos: position{line: 61, col: 16, offset: 1603},
								expr: &ruleRefExpr{
									pos:  position{line: 61, col: 16, offset: 1603},
									name: "comment",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 61, col: 25, offset: 1612},
								name: "eol",
							},
							&zeroOrMoreExpr{
								pos: position{line: 61, col: 29, offset: 1616},
								expr: &ruleRefExpr{
									pos:  position{line: 61, col: 29, offset: 1616},
									name: "line",
								},
							},
							&litMatcher{
								pos:        position{line: 61, col: 35, offset: 1622},
								val:        "}",
								ignoreCase: false,
								want:       "\"}\"",
							},
							&zeroOrMoreExpr{
								pos: position{line: 61, col: 39, offset: 1626},
								expr: &ruleRefExpr{
									pos:  position{line: 61, col: 39, offset: 1626},
									name: "comment",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 61, col: 48, offset: 1635},
								name: "eol",
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 61, col: 54, offset: 1641},
						name: "eof",
					},
				},
			},
		},
		{
			name: "identifier_list",
			pos:  position{line: 62, col: 1, offset: 1646},
			expr: &seqExpr{
				pos: position{line: 62, col: 18, offset: 1663},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 62, col: 18, offset: 1663},
						name: "identifier",
					},
					&seqExpr{
						pos: position{line: 62, col: 30, offset: 1675},
						exprs: []any{
							&oneOrMoreExpr{
								pos: position{line: 62, col: 30, offset: 1675},
								expr: &ruleRefExpr{
									pos:  position{line: 62, col: 30, offset: 1675},
									name: "ws",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 62, col: 34, offset: 1679},
								name: "identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "argument_decl",
			pos:  position{line: 63, col: 1, offset: 1692},
			expr: &seqExpr{
				pos: position{line: 63, col: 17, offset: 1708},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 63, col: 17, offset: 1708},
						val:        "(",
						ignoreCase: false,
						want:       "\"(\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 63, col: 21, offset: 1712},
						expr: &ruleRefExpr{
							pos:  position{line: 63, col: 21, offset: 1712},
							name: "ws",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 63, col: 25, offset: 1716},
						name: "identifier_list",
					},
					&zeroOrMoreExpr{
						pos: position{line: 63, col: 41, offset: 1732},
						expr: &ruleRefExpr{
							pos:  position{line: 63, col: 41, offset: 1732},
							name: "ws",
						},
					},
					&litMatcher{
						pos:        position{line: 63, col: 45, offset: 1736},
						val:        ")",
						ignoreCase: false,
						want:       "\")\"",
					},
				},
			},
		},
		{
			name: "lambda",
			pos:  position{line: 64, col: 1, offset: 1742},
			expr: &seqExpr{
				pos: position{line: 64, col: 10, offset: 1751},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 64, col: 10, offset: 1751},
						name: "argument_decl",
					},
					&zeroOrMoreExpr{
						pos: position{line: 64, col: 24, offset: 1765},
						expr: &ruleRefExpr{
							pos:  position{line: 64, col: 24, offset: 1765},
							name: "ws",
						},
					},
					&labeledExpr{
						pos:   position{line: 64, col: 28, offset: 1769},
						label: "_e",
						expr: &choiceExpr{
							pos: position{line: 64, col: 32, offset: 1773},
							alternatives: []any{
								&ruleRefExpr{
									pos:  position{line: 64, col: 32, offset: 1773},
									name: "block",
								},
								&ruleRefExpr{
									pos:  position{line: 64, col: 40, offset: 1781},
									name: "expression",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "assign",
			pos:  position{line: 66, col: 1, offset: 1796},
			expr: &actionExpr{
				pos: position{line: 66, col: 10, offset: 1805},
				run: (*parser).callonassign1,
				expr: &seqExpr{
					pos: position{line: 66, col: 10, offset: 1805},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 66, col: 10, offset: 1805},
							label: "_i",
							expr: &ruleRefExpr{
								pos:  position{line: 66, col: 13, offset: 1808},
								name: "identifier",
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 66, col: 24, offset: 1819},
							expr: &ruleRefExpr{
								pos:  position{line: 66, col: 24, offset: 1819},
								name: "ws",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 66, col: 28, offset: 1823},
							name: "eq",
						},
						&zeroOrMoreExpr{
							pos: position{line: 66, col: 31, offset: 1826},
							expr: &ruleRefExpr{
								pos:  position{line: 66, col: 31, offset: 1826},
								name: "ws",
							},
						},
						&labeledExpr{
							pos:   position{line: 66, col: 35, offset: 1830},
							label: "_e",
							expr: &choiceExpr{
								pos: position{line: 66, col: 39, offset: 1834},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 66, col: 39, offset: 1834},
										name: "expression",
									},
									&ruleRefExpr{
										pos:  position{line: 66, col: 52, offset: 1847},
										name: "lambda",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "writeln",
			pos:  position{line: 73, col: 1, offset: 1951},
			expr: &seqExpr{
				pos: position{line: 73, col: 11, offset: 1961},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 73, col: 11, offset: 1961},
						name: "gt",
					},
					&zeroOrMoreExpr{
						pos: position{line: 73, col: 14, offset: 1964},
						expr: &ruleRefExpr{
							pos:  position{line: 73, col: 14, offset: 1964},
							name: "ws",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 73, col: 18, offset: 1968},
						name: "expression",
					},
				},
			},
		},
		{
			name: "write",
			pos:  position{line: 74, col: 1, offset: 1980},
			expr: &seqExpr{
				pos: position{line: 74, col: 9, offset: 1988},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 74, col: 9, offset: 1988},
						name: "pipe",
					},
					&zeroOrMoreExpr{
						pos: position{line: 74, col: 14, offset: 1993},
						expr: &ruleRefExpr{
							pos:  position{line: 74, col: 14, offset: 1993},
							name: "ws",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 74, col: 18, offset: 1997},
						name: "expression",
					},
				},
			},
		},
		{
			name: "invoke",
			pos:  position{line: 75, col: 1, offset: 2009},
			expr: &seqExpr{
				pos: position{line: 75, col: 10, offset: 2018},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 75, col: 10, offset: 2018},
						name: "amper",
					},
					&ruleRefExpr{
						pos:  position{line: 75, col: 16, offset: 2024},
						name: "expression",
					},
				},
			},
		},
		{
			name: "identifier",
			pos:  position{line: 77, col: 1, offset: 2038},
			expr: &actionExpr{
				pos: position{line: 77, col: 14, offset: 2051},
				run: (*parser).callonidentifier1,
				expr: &seqExpr{
					pos: position{line: 77, col: 14, offset: 2051},
					exprs: []any{
						&choiceExpr{
							pos: position{line: 77, col: 15, offset: 2052},
							alternatives: []any{
								&ruleRefExpr{
									pos:  position{line: 77, col: 15, offset: 2052},
									name: "unds",
								},
								&ruleRefExpr{
									pos:  position{line: 77, col: 22, offset: 2059},
									name: "let",
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 77, col: 27, offset: 2064},
							expr: &choiceExpr{
								pos: position{line: 77, col: 28, offset: 2065},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 77, col: 28, offset: 2065},
										name: "dig",
									},
									&ruleRefExpr{
										pos:  position{line: 77, col: 34, offset: 2071},
										name: "unds",
									},
									&ruleRefExpr{
										pos:  position{line: 77, col: 41, offset: 2078},
										name: "let",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "literal_list",
			pos:  position{line: 79, col: 1, offset: 2118},
			expr: &actionExpr{
				pos: position{line: 79, col: 16, offset: 2133},
				run: (*parser).callonliteral_list1,
				expr: &seqExpr{
					pos: position{line: 79, col: 16, offset: 2133},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 79, col: 16, offset: 2133},
							label: "l",
							expr: &ruleRefExpr{
								pos:  position{line: 79, col: 18, offset: 2135},
								name: "literal",
							},
						},
						&labeledExpr{
							pos:   position{line: 79, col: 26, offset: 2143},
							label: "r",
							expr: &zeroOrMoreExpr{
								pos: position{line: 79, col: 28, offset: 2145},
								expr: &actionExpr{
									pos: position{line: 79, col: 29, offset: 2146},
									run: (*parser).callonliteral_list7,
									expr: &seqExpr{
										pos: position{line: 79, col: 29, offset: 2146},
										exprs: []any{
											&oneOrMoreExpr{
												pos: position{line: 79, col: 29, offset: 2146},
												expr: &ruleRefExpr{
													pos:  position{line: 79, col: 29, offset: 2146},
													name: "ws",
												},
											},
											&labeledExpr{
												pos:   position{line: 79, col: 33, offset: 2150},
												label: "t",
												expr: &ruleRefExpr{
													pos:  position{line: 79, col: 35, offset: 2152},
													name: "literal",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "literal",
			pos:  position{line: 84, col: 1, offset: 2252},
			expr: &actionExpr{
				pos: position{line: 84, col: 11, offset: 2262},
				run: (*parser).callonliteral1,
				expr: &labeledExpr{
					pos:   position{line: 84, col: 11, offset: 2262},
					label: "t",
					expr: &choiceExpr{
						pos: position{line: 84, col: 15, offset: 2266},
						alternatives: []any{
							&actionExpr{
								pos: position{line: 84, col: 15, offset: 2266},
								run: (*parser).callonliteral4,
								expr: &oneOrMoreExpr{
									pos: position{line: 84, col: 15, offset: 2266},
									expr: &ruleRefExpr{
										pos:  position{line: 84, col: 15, offset: 2266},
										name: "lit",
									},
								},
							},
							&actionExpr{
								pos: position{line: 84, col: 52, offset: 2303},
								run: (*parser).callonliteral7,
								expr: &labeledExpr{
									pos:   position{line: 84, col: 52, offset: 2303},
									label: "s",
									expr: &ruleRefExpr{
										pos:  position{line: 84, col: 54, offset: 2305},
										name: "quotedString",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "lit",
			pos:  position{line: 89, col: 1, offset: 2393},
			expr: &choiceExpr{
				pos: position{line: 89, col: 7, offset: 2399},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 89, col: 7, offset: 2399},
						name: "sym",
					},
					&ruleRefExpr{
						pos:  position{line: 89, col: 13, offset: 2405},
						name: "let",
					},
					&ruleRefExpr{
						pos:  position{line: 89, col: 19, offset: 2411},
						name: "dig",
					},
				},
			},
		},
		{
			name: "dig",
			pos:  position{line: 90, col: 1, offset: 2416},
			expr: &charClassMatcher{
				pos:        position{line: 90, col: 7, offset: 2422},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "let",
			pos:  position{line: 91, col: 1, offset: 2429},
			expr: &charClassMatcher{
				pos:        position{line: 91, col: 7, offset: 2435},
				val:        "[a-zA-Z]",
				ranges:     []rune{'a', 'z', 'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "sym",
			pos:  position{line: 92, col: 1, offset: 2445},
			expr: &choiceExpr{
				pos: position{line: 92, col: 7, offset: 2451},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 92, col: 7, offset: 2451},
						name: "dash",
					},
					&ruleRefExpr{
						pos:  position{line: 92, col: 14, offset: 2458},
						name: "unds",
					},
					&ruleRefExpr{
						pos:  position{line: 92, col: 21, offset: 2465},
						name: "slsh",
					},
					&ruleRefExpr{
						pos:  position{line: 92, col: 28, offset: 2472},
						name: "bslh",
					},
				},
			},
		},
		{
			name: "ws",
			pos:  position{line: 94, col: 1, offset: 2480},
			expr: &choiceExpr{
				pos: position{line: 94, col: 6, offset: 2485},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 94, col: 6, offset: 2485},
						val:        " ",
						ignoreCase: false,
						want:       "\" \"",
					},
					&litMatcher{
						pos:        position{line: 94, col: 12, offset: 2491},
						val:        "\t",
						ignoreCase: false,
						want:       "\"\\t\"",
					},
				},
			},
		},
		{
			name: "dash",
			pos:  position{line: 95, col: 1, offset: 2497},
			expr: &litMatcher{
				pos:        position{line: 95, col: 8, offset: 2504},
				val:        "-",
				ignoreCase: false,
				want:       "\"-\"",
			},
		},
		{
			name: "unds",
			pos:  position{line: 96, col: 1, offset: 2509},
			expr: &litMatcher{
				pos:        position{line: 96, col: 8, offset: 2516},
				val:        "_",
				ignoreCase: false,
				want:       "\"_\"",
			},
		},
		{
			name: "slsh",
			pos:  position{line: 97, col: 1, offset: 2521},
			expr: &litMatcher{
				pos:        position{line: 97, col: 8, offset: 2528},
				val:        "/",
				ignoreCase: false,
				want:       "\"/\"",
			},
		},
		{
			name: "bslh",
			pos:  position{line: 98, col: 1, offset: 2533},
			expr: &litMatcher{
				pos:        position{line: 98, col: 8, offset: 2540},
				val:        "\\",
				ignoreCase: false,
				want:       "\"\\\\\"",
			},
		},
		{
			name: "quot",
			pos:  position{line: 99, col: 1, offset: 2546},
			expr: &litMatcher{
				pos:        position{line: 99, col: 8, offset: 2553},
				val:        "`",
				ignoreCase: false,
				want:       "\"`\"",
			},
		},
		{
			name: "sign",
			pos:  position{line: 100, col: 1, offset: 2558},
			expr: &litMatcher{
				pos:        position{line: 100, col: 8, offset: 2565},
				val:        "$",
				ignoreCase: false,
				want:       "\"$\"",
			},
		},
		{
			name: "pipe",
			pos:  position{line: 101, col: 1, offset: 2570},
			expr: &litMatcher{
				pos:        position{line: 101, col: 8, offset: 2577},
				val:        "|",
				ignoreCase: false,
				want:       "\"|\"",
			},
		},
		{
			name: "gt",
			pos:  position{line: 102, col: 1, offset: 2582},
			expr: &litMatcher{
				pos:        position{line: 102, col: 6, offset: 2587},
				val:        ">",
				ignoreCase: false,
				want:       "\">\"",
			},
		},
		{
			name: "eq",
			pos:  position{line: 103, col: 1, offset: 2592},
			expr: &litMatcher{
				pos:        position{line: 103, col: 6, offset: 2597},
				val:        "=",
				ignoreCase: false,
				want:       "\"=\"",
			},
		},
		{
			name: "amper",
			pos:  position{line: 104, col: 1, offset: 2602},
			expr: &litMatcher{
				pos:        position{line: 104, col: 9, offset: 2610},
				val:        "&",
				ignoreCase: false,
				want:       "\"&\"",
			},
		},
		{
			name: "tilda",
			pos:  position{line: 105, col: 1, offset: 2615},
			expr: &litMatcher{
				pos:        position{line: 105, col: 9, offset: 2623},
				val:        "~",
				ignoreCase: false,
				want:       "\"~\"",
			},
		},
		{
			name: "any",
			pos:  position{line: 107, col: 1, offset: 2630},
			expr: &anyMatcher{
				line: 107, col: 7, offset: 2636,
			},
		},
		{
			name: "eof",
			pos:  position{line: 108, col: 1, offset: 2639},
			expr: &notExpr{
				pos: position{line: 108, col: 7, offset: 2645},
				expr: &anyMatcher{
					line: 108, col: 8, offset: 2646,
				},
			},
		},
	},
}

func (c *current) online4(code any) (any, error) {
	return code, nil
}

func (p *parser) callonline4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.online4(stack["code"])
}

func (c *current) oncomment1() (any, error) {
	return string(c.text), nil
}

func (p *parser) calloncomment1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.oncomment1()
}

func (c *current) ondirective1(directive any) (any, error) {
	return directive, nil
}

func (p *parser) callondirective1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.ondirective1(stack["directive"])
}

func (c *current) oninclude1(fn any) (any, error) {
	return Include{FileName: fn.(Literal)}, nil
}

func (p *parser) calloninclude1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.oninclude1(stack["fn"])
}

func (c *current) onquotedString3() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonquotedString3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onquotedString3()
}

func (c *current) onsingleQuotedString1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonsingleQuotedString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onsingleQuotedString1()
}

func (c *current) ondoubleQuotedString1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callondoubleQuotedString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.ondoubleQuotedString1()
}

func (c *current) onindex1(_e any) (any, error) {
	return _e, nil
}

func (p *parser) callonindex1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onindex1(stack["_e"])
}

func (c *current) onmember1(_m, _e any) (any, error) {

	return Member{
		Identifier: castify(_m, ""),
		Indexes:    arrayify[Expression](_e)}, nil
}

func (p *parser) callonmember1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onmember1(stack["_m"], stack["_e"])
}

func (c *current) onmember_list1(_m, _r any) (any, error) {

	return (MemberList)(listFrom[Member](_m, _r)), nil
}

func (p *parser) callonmember_list1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onmember_list1(stack["_m"], stack["_r"])
}

func (c *current) onreference6(_m any) (any, error) {
	return _m, nil
}

func (p *parser) callonreference6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onreference6(stack["_m"])
}

func (c *current) onreference11(_m any) (any, error) {
	return _m, nil
}

func (p *parser) callonreference11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onreference11(stack["_m"])
}

func (c *current) onreference1(_m any) (any, error) {

	return _m, nil

}

func (p *parser) callonreference1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onreference1(stack["_m"])
}

func (c *current) onexpression7(_e any) (any, error) {
	return _e, nil
}

func (p *parser) callonexpression7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onexpression7(stack["_e"])
}

func (c *current) onassign1(_i, _e any) (any, error) {

	return Assign{
		Identifier: castify(_i, ""),
		Value:      _e.(Expression)}, nil
}

func (p *parser) callonassign1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onassign1(stack["_i"], stack["_e"])
}

func (c *current) onidentifier1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonidentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onidentifier1()
}

func (c *current) onliteral_list7(t any) (any, error) {
	return t, nil
}

func (p *parser) callonliteral_list7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onliteral_list7(stack["t"])
}

func (c *current) onliteral_list1(l, r any) (any, error) {

	return (LiteralList)(listFrom[Literal](l, r)), nil

}

func (p *parser) callonliteral_list1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onliteral_list1(stack["l"], stack["r"])
}

func (c *current) onliteral4() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonliteral4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onliteral4()
}

func (c *current) onliteral7(s any) (any, error) {
	return s, nil
}

func (p *parser) callonliteral7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onliteral7(stack["s"])
}

func (c *current) onliteral1(t any) (any, error) {

	return LiteralMake(t.(string)), nil

}

func (p *parser) callonliteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onliteral1(stack["t"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
